### ISSUE TITLE
Script still functioning with High Sierra?

### ISSUE THREAD

**Issue by mrtimothyduong** [vmwaredevcenter/AirWatch---Shell-Script-to-Install-Microsoft-Office-2016-for-Mac#2]
Hi,

Attempting to run this directly from the device for troubleshooting purposes:

Eg:
`sudo sh ./office2016script.sh`

Result:
`syntax error near unexpected token 'do
'do`

Checked the Pull Request and still getting the same error. Any recommendations?

Regards,

Timothy

**Comment by digitalsr2** [comment]
I'm having the same issue. Wondering if this is still supported in High Sierra.

**Comment by rterakedis** [comment]
Found an issue with a previous commit introducing hidden characters in the file.  Just replaced the file with the original and it wasn't failing with any errors on my 10.13.3 machine.
